name: dio_retry
description: A starting point for Dart libraries or applications.
version: 0.1.10-beta
homepage: https://github.com/aloisdeniel/dio_retry
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  logging: ^1.0.0
  dio: ^4.0.0-beta7

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
